### PR TITLE
change default ports

### PR DESCRIPTION
**Pull request by eolesinski**
This PR addresses issue #97 by updating the port numbers used in the `raft_test.cpp` unit tests to a higher range (29800-29802) to avoid conflicts with commonly used ports.

Port conflicts with 5000 are frequent, especially with the docker-registry and Apple's AirPlay Receiver on MacOS. To address this issue, the default ports are updated to 298xx, following the convention outlined in #259.

Tested: tested by running `./scripts/test.sh` 

**EDIT:** This change now updates all test endpoints that use ports at 5xxx

### CODE REVIEW

**Comment by HalosGhost** [comment]
It looks like there are a ~lot of~few other tests which use 5xxx portnumbers; are you hoping to address those all in this PR as well?

In particular, the `cfg` files used by the integration test suites.

**Comment by eolesinski** [comment]
@HalosGhost Yep - I can go through the other tests and make those changes

**Review by maurermi — APPROVED** [review]
T-ACK. This is useful when running on my local system since port 5000 is often occupied. I approve of these changes but second @HalosGhost 's comment that this should be replicated elsewhere in the code.

**Review by maurermi — APPROVED** [review]
T-ACK. Updates the ports-used-for-test to be outside the range of typically used ports. MacOS AirPlay users rejoice.

**Review by HalosGhost — APPROVED** [review]
T-ACK. Just swaps out the default ports we use to something less crowded. Hopefully defaults to causing far fewer headaches!

Thanks @eolesinski

**Pull request merged**
