### PR TITLE
fix: ensure -builder docker image gets built

### PR DESCRIPTION
**Pull request by HalosGhost**
cf. @curiousHG [asking about this problem on Zulip](https://opencbdc.zulipchat.com/#narrow/stream/315624-General/topic/Testing.20Infrstructure/near/321198482)

### CODE REVIEW

**Comment by curiousHG** [comment]
It started to work.

**Comment by HalosGhost** [comment]
I noticed that the `atomizer` image is also no longer built. I'll go ahead and add that one as well, and make sure the README is up-to-date. Once done, I'll merge in.

**Comment by HalosGhost** [comment]
@AlexRamRam or @maurermi (or @curiousHG, of course!); would any of you be able to officially offer a review/ACK before I merge?

**Comment by AlexRamRam** [comment]
Tested ACK

**Pull request merged**
