### PR TITLE
Upgrade from c++17 to c++20

### LINKED ISSUE #237: Upgrade build to c++20

### PR DESCRIPTION
**Pull request by AlexRamRam**
Fix #237

### CODE REVIEW

**Comment by maurermi** [comment]
concept-ACK, I think this is a good idea -- will test soon

**Comment by HalosGhost** [comment]
Concept ACK (we had initially avoided 20 till Bitcoin switches, but given we now have dependencies which will require switching, I think that ship has sailed); reminder we need to test basic performance impact locally and in test controller.

**Review by maurermi — APPROVED** [review]
T-ACK. Tested using Docker and all tests pass. Did not explicitly evaluate performance impact at this time relative to the C++17 build but changes are minimal and it would be quite surprising if this impacted performance as far as I can tell. 

The question remains of when exactly we want to make this switch. Sooner seems better than later since later developments may depend on C++20. 

Edit: Appended this commit to trunk for the test, can confirm that this change works with current state of trunk.

**Comment by HalosGhost** [comment]
tACK. I've checked rebased against the latest trunk, and done some local performance comparisons (no performance degradation is visible; if anything, I see slightly higher sustained throughput for identical configurations).

LGTM. Merging.

**Review by HalosGhost — APPROVED** [review]

**Pull request merged**
