### PR TITLE
Check preconditions for init methods for locking shard and coordinator controllers

### PR DESCRIPTION
**Pull request by mszulcz-mitre**
This pull request addresses Issue #153.  It contains the following:

- commits that check preconditions of the `init` methods for `cbdc::controller::controller` and `cbdc::locking_shard::controller`
- unit tests for the `init` methods
- an extension to the test script, `test.sh`, that allows unit tests to use configuration files

### CODE REVIEW

**Review by HalosGhost — APPROVED** [review]
Tested ACK. This is a reasonably simple change to make the locking shard and coordinator controller initializations a little more robust.

**Comment by HalosGhost** [comment]
@mszulcz-mitre can you squash these to semantic commits and I'll be ready for merge?

**Comment by mszulcz-mitre** [comment]
@HalosGhost I squashed the commits based on my understanding from our previous conversation.

**Comment by HalosGhost** [comment]
Looks perfect, thank you! Merging.

**Pull request merged**
