### PR TITLE
Sharded_DB branch

### PR DESCRIPTION
**Pull request by natecable**

### CODE REVIEW

**Comment by maurermi** [comment]
Hi @natecable, thanks for PRing this looking forward to reviewing it. I am interested in seeing what OracleDB makes possible in OpenCBDC. Haven't had a chance to look in depth yet, but here are a couple quick notes that would help us with the review process.

1. We use a DCO check, which requires all commits to contain a "Signed-off-by" line. This can be done automatically using `git commit -s`.
2. It would be great if some of these commits were squashed together where possible, specifically those that correspond to the same proposed change. We generally aim to have each commit cover one feature change (or a small set of feature changes) in the code, and look to give each commit a description of what the change is (typically a high-level one line description, followed by a more in depth description when necessary). This helps us understand all the changes proposed when we conduct a review, and in the future helps us understand the code history.

These could probably be tackled at the same time, and would help the process quite a bit! Happy to answer any questions as well.

**Comment by natecable** [comment]
Sorry about that! These changes were accidentally submitted to the original
branch as well as my team’s personal fork. My bad!

**Comment by maurermi** [comment]
@natecable No worries!

**Comment by HalosGhost** [comment]
@natecable I'm going to close this now, but feel free to reopen if you'd like it to be considered for inclusion upstream!

**Pull request closed without merging**
