### PR TITLE
Disable RTTI and fix macOS builds

### PR DESCRIPTION
**Pull request by dmtrinh**
Resolves build failures on macOS/Darwin - issue #36.  Replacement for PR #55; please refer to that PR for prior thread with @metalicjames.  Note that disabling RTTI should also allow us to build against the latest LevelDB 1.23 on Linux.

### CODE REVIEW

**Comment by HalosGhost** [comment]
@dmtrinh there are still merge commits in this PR. `git rebase origin/trunk` should actually automatically remove merge commits, so that's probably the next thing to do (reading up on [rebasing](https://git-scm.com/docs/git-rebase) may be useful too).

If it's easier/quicker, I can also cherry-pick the two commits into a separate PR and merge.

**Review by HalosGhost — CHANGES_REQUESTED** [review]
Needs squashing.

**Comment by dmtrinh** [comment]
> Needs squashing.

@HalosGhost Merge commits are part of the set to be squashed so git is complaining. :-(  It might be quicker if you cherry-pick the one commit [4754f5d](https://github.com/mit-dci/opencbdc-tx/pull/64/commits/4754f5d7846e938ee4907e9f5376e6442f2a845f) on your side.  Just let me know how you'd like to proceed...  Thanks!

**Comment by HalosGhost** [comment]
@dmtrinh okay, I just checked out your work locally and I know what happened (it's from this branch attempting to build off your trunk branch rather than starting sync'd with `upstream/trunk`). In short, it's trying to re-apply d415932 which is why the merge commits are showing up. 

I've opened #65 as a replacement PR and will merge after all checks pass.

After it's merged, I'd strongly suggest resyncing your `trunk` branch with upstream's `trunk` (it may make sense for us to add a bit of guidance on how to do this since it will be a frequent requirement). The easiest way to do this (in my opinion) is to add an `upstream` remote:

```console
$ git remote add upstream 'https://github.com/mit-dci/opencbdc-tx'
```

Once you have an `upstream` remote, you can do the following to sync your local `trunk`:

```console
$ git switch trunk
$ git pull upstream trunk
```

Because your fork's `trunk` differs from `upstream/trunk`, you may need to do something a little more aggressive (e.g., using ``--force``); this is a reason why it is much easier to leave your fork's `trunk` as little more than a shortcut and to do most/all work that you intend to PR on other branches (so that syncing `trunk` is always trivial). I hope that explanation helped!

**Comment by dmtrinh** [comment]
Very helpful as always, thanks Sam!!

**Pull request closed without merging**
