### PR TITLE
Added protobuf serialization

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by HalosGhost** [comment]
This looks very interesting! Can you read through the [IP section of the Contribution Guide](https://github.com/mit-dci/opencbdc-tx/blob/trunk/docs/contributing.md#intellectual-property) and rebase your PR including a DCO on your commit?

After a DCO is added, I'll run the workflow and review the PR itself.

**Comment by ghost** [comment]
The code is not ready for PR

**Comment by HalosGhost** [comment]
You're welcome to reopen it and mark it as a draft!

**Comment by HalosGhost** [comment]
In addition, it's not really clear to me what benefit protobuf would bring to the project. I would be happy to chat with you about it on the [Zulip](https://opencbdc.zulipchat.com) to help determine the potential benefits.

**Pull request closed without merging**
