### PR TITLE
fix: Retry sentinel startup on failure

### LINKED ISSUE #186: Part of "Run the Code" section in README.md appears broken
### Affected Branch

trunk

### Basic Diagnostics

- [X] I've pulled the latest changes on the affected branch and the issue is still present.

- [X] The issue is reproducible in docker

### Description

In the "Run the Code" section of README.md, the following step hangs:

> * Send currency from the first wallet to the second wallet created in the previous step (e.g., 30 atomic units of currency)
>   ```terminal
>   # ./build/src/uhs/client/client-cli 2pc-compose.cfg mempool0.dat wallet0.dat send 30 <wallet address>
>   ```
where `<wallet address>` is the address returned from running the `client-cli` with the `newaddress` keyword.

I followed the instructions in the sections "Launch the System" and "Setup test wallets and test them" for the 2PC architecture.  The instructions are:

> 1. Run the System
>    ```terminal
>    # docker compose --file docker-compose-2pc.yml up --build
>    ```
> 1. Launch a container in which to run wallet commands (use `--network atomizer-network` instead of `--network 2pc-network` if using the atomizer architecture)
>    ```terminal
>    # docker run --network 2pc-network -ti opencbdc-tx /bin/bash
>    ```
> * Mint new coins (e.g., 10 new UTXOs each with a value of 5 atomic units of currency)
>   ```terminal
>   # ./build/src/uhs/client/client-cli 2pc-compose.cfg mempool0.dat wallet0.dat mint 10 5
>   [2021-08-17 15:11:57.686] [WARN ] Existing wallet file not found
>   [2021-08-17 15:11:57.686] [WARN ] Existing mempool not found
>   4bc23da407c3a8110145c5b6c38199c8ec3b0e35ea66bbfd78f0ed65304ce6fa
>   ```
> 
> * Inspect the balance of a wallet
>   ```terminal
>   # ./build/src/uhs/client/client-cli 2pc-compose.cfg mempool0.dat wallet0.dat info
>   Balance: $0.50, UTXOs: 10, pending TXs: 0
>   ```
> 
> * Make a new wallet
>   ```terminal
>   # ./build/src/uhs/client/client-cli 2pc-compose.cfg mempool1.dat wallet1.dat newaddress
>   [2021-08-17 15:13:16.148] [WARN ] Existing wallet file not found
>   [2021-08-17 15:13:16.148] [WARN ] Existing mempool not found
>   usd1qrw038lx5n4wxx3yvuwdndpr7gnm347d6pn37uywgudzq90w7fsuk52kd5u
>   ```
> 
> * Send currency from the first wallet to the second wallet created in the previous step (e.g., 30 atomic units of currency)
>   ```terminal
>   # ./build/src/uhs/client/client-cli 2pc-compose.cfg mempool0.dat wallet0.dat send 30 usd1qrw038lx5n4wxx3yvuwdndpr7gnm347d6pn37uywgudzq90w7fsuk52kd5u

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by HalosGhost**
In particular, infinitely retry starting the sentinel if its coordinator client fails to initialize.

Note: this probably isn't ideal; exponential back-off delay with a retry threshold (after which we should fatally error out) is probably better in the long-run. This, however, will suffice for now.

*Edit*: As infinite-retry causes the tests to fail, I've gone ahead and implemented a really basic threshold and increasing-delay. Currently, the threshold is `4` retries, and the delay is exponential (increasing by a factor of two). I will be double-checking that the README walkthrough runs correctly (on a reasonably low-powered machine of mine) after the tests pass before I request review from someone else to try to make sure this will fix the issue (at least for most people).

Fixes #186

### CODE REVIEW

**Comment by HalosGhost** [comment]
CC: @karlovskiy, @mszulcz-mitre, @AlexRamRam, @metalicjames 

Would any of you mind pulling this change and testing locally. It seems to work quite reliably on my two test machines (one of which is woefully under-powered), but I'd love to get a second tACK before I merge it.

**Comment by karlovskiy** [comment]
@HalosGhost  I've had chance to check your commit and it just works!

**Comment by HalosGhost** [comment]
I'm considering that a tACK from @karlovskiy. I'll add my own approval just for record-keeping. Merging.

**Comment by HalosGhost** [comment]
@karlovskiy want to request your own review and add an approval? PR authors cannot approve their own PRs. :)

**Comment by karlovskiy** [comment]
@HalosGhost  Ok. I'll be glad to ;)

**Review by darbha-ram — APPROVED** [review]
Tested startup and basic wallet operations, they work.

**Pull request merged**
