### PR TITLE
Removed extraneous \return command for Doxygen

### LINKED ISSUE #52: Incorrect return type in header files causing Doxygen to fail
### Affected Branch

trunk

### Basic Diagnostics

- [X] I've pulled the latest changes on the affected branch and the issue is still present.

- [ ] The issue is reproducible in docker

### Description

A few header files have extraneous /return commands causing Doxygen to fail.  These appear to be innocent typos due to copy/paste.

In order to reproduce the issue, follow these steps:

1.   Clone repo
```
git clone --recurse-submodules https://github.com/mit-dci/opencbdc-tx
```
2.   Run Doxygen
```
doxygen Doxyfile
```
The errors you'll eventually see are:
```
...
Generating call graph for function cbdc::transaction::wallet::seed
/Users/duc/Dev2/opencbdc-tx_dmt/src/uhs/transaction/wallet.hpp:142: error: documented empty return type of cbdc::transaction::wallet::seed_readonly (warning treated as error, aborting now)
...
Generating call graph for function cbdc::watchtower::error_cache::check_tx_id
/Users/duc/Dev2/opencbdc-tx_dmt/src/uhs/atomizer/watchtower/error_cache.hpp:36: error: documented empty return type of cbdc::watchtower::error_cache::push_errors (warning treated as error, aborting now)
Exiting...


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dmtrinh**
Very minor fix for #52.  All tests passed.  Full Doxygen run log attached
[out.txt](https://github.com/mit-dci/opencbdc-tx/files/8054874/out.txt)
.

### CODE REVIEW

**Review by HalosGhost — CHANGES_REQUESTED** [review]
This looks like a very simple solution to an obvious copy-paste error. Thank you!

However, it looks like this commit doesn't contain a sign-off; please read through [the IP section of the Contribution Guide](https://github.com/mit-dci/opencbdc-tx/blob/trunk/docs/contributing.md#intellectual-property) and follow the instructions to add a sign-off.

**Comment by HalosGhost** [comment]
(We're hoping to get an automated DCO check added this next week so that the CI itself will flag when a DCO hasn't been included.)

**Comment by dmtrinh** [comment]
> This looks like a very simple solution to an obvious copy-paste error. Thank you!
> 
> However, it looks like this commit doesn't contain a sign-off; please read through [the IP section of the Contribution Guide](https://github.com/mit-dci/opencbdc-tx/blob/trunk/docs/contributing.md#intellectual-property) and follow the instructions to add a sign-off.

Sorry about the oversight!  Just amended the commit and [Force-pushed](https://www.starwars.com/databank/force-push). :)

**Review by HalosGhost — APPROVED** [review]
Following the amendment, this looks perfect to me. Will merge after final CI double-check.

**Comment by HalosGhost** [comment]
Merging.

**Pull request merged**
