### PR TITLE
Arch linux snappy

### LINKED ISSUE #171: Multiple occurences of unresolved symbols from snappy in leveldb
### Affected Branch

trunk

### Basic Diagnostics

- [X] I've pulled the latest changes on the affected branch and the issue is still present.

- [ ] The issue is reproducible in docker

### Description

Only example of error message from build. Multiple unresolved symbols from snappy library when building on Arch Linux.
```
[ 73%] Building CXX object src/uhs/twophase/sentinel_2pc/CMakeFiles/sentineld-2pc.dir/sentineld_2pc.o
/usr/bin/ld: /usr/local/lib/libleveldb.a(table_builder.cc.o): in function `leveldb::port::Snappy_Compress(char const*, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
/home/prauat/projects/opencbdc-tx/leveldb-1.22-Debug/port/port_stdcxx.h:91: undefined reference to `snappy::MaxCompressedLength(unsigned long)'
/usr/bin/ld: /home/prauat/projects/opencbdc-tx/leveldb-1.22-Debug/port/port_stdcxx.h:93: undefined reference to `snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)'
/usr/bin/ld: /usr/local/lib/libleveldb.a(format.cc.o): in function `leveldb::port::Snappy_GetUncompressedLength(char const*, unsigned long, unsigned long*)':
/home/prauat/projects/opencbdc-tx/leveldb-1.22-Debug/port/port_stdcxx.h:109: undefined reference to `snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)'
/usr/bin/ld: /usr/local/lib/libleveldb.a(format.cc.o): in function `leveldb::port::Snappy_Uncompress(char const*, unsigned long, char*)':
/home/prauat/projects/opencbdc-tx/leveldb-1.22-Debug/port/port_stdcxx.h:121: undefined reference to `snappy::RawUncompress(char const*, unsigned long, char*)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/uhs/atomizer/archiver/CMakeFiles/archiverd.dir/build.make:108: src/uhs/atomizer/archiver/archiverd] Błąd 1
make[1]: *** [CMakeFiles/Makefile2:774: src/uhs/atomizer/archiver/CMakeFiles/archiverd.dir/all] Błąd 2
make[1]: *** Oczekiwanie na niezakończone zadania....
/usr/bin/ld: /usr/local/lib/libleveldb.a(table_builder.cc.o): in function `leveldb::port::Snappy_Compress(char const*, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
/home/prauat/projects/opencbdc-tx/leveldb-1.22-Debug/port/port_stdcxx.h:91: undefined reference to `snappy::MaxCompressedLength(unsigned long)'
/usr/bin/ld: /home/prauat/projects/opencbdc-tx/leveldb-1.22-Debug/port/port_stdcxx.h:93: undefined reference to `snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)'
/usr/bin/ld: /usr/local/lib/libleveldb.a(format.cc.o): in function `leveldb::port::Snappy_GetUncompressedLength(char const*, unsigned long, unsigned long*)':
/home/prauat/projects/opencbdc-tx/leveldb-1.22-Debug/port/port_stdcxx.h:109: undefined reference to `snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)'
/usr/bin/ld: /usr/local/lib/libleveldb.a(format.cc.o): in function `leveldb::port::Snappy_Uncompress(char const*, unsigned long, char*)':
/home/prauat/projects/opencbdc-tx/leveldb-1.22-Debug/port/port_stdcxx.h:121: undefined reference to `snappy::RawUncompress(char const*, unsigned long, char*)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/uhs/twophase/locking_shard/CMakeFiles/locking-shardd.dir/build.make:108: src/uhs/twophase/locking_shard/locking-shardd] Błąd 1
make[1]: *** [CMakeFiles/Makefile2:1281: src/uhs/twophase/locking_shard/CMakeFiles/locking-shardd.dir/all] Błąd 2
```
In order to reproduce the issue, follow these steps:

1. scripts/configure.sh
2. scripts/build.sh

Well it looks like snappy should be added to CMakeList.txt in multiple files using check_library_exists() and target_link_libraries().

Proposed changes can be viewed [arch-linux-snappy](https://github.com/mit-dci/opencbdc-tx/compare/trunk...pr4u4t:opencbdc-tx:arch-linux-snappy). Let me know if pull request is desired.  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pr4u4t**
#171 according to my last comment ```check_library_exists(snappy snappy_compress "" HAVE_SNAPPY)``` should be changed to ```find_library(SNAPPY_LIBRARY snappy REQUIRED)``` as this library is needed by LevelDB and if shared only exists on the system it must be added to target linking.

### CODE REVIEW

**Comment by HalosGhost** [comment]
solid Concept ACK. Can you rebase on `trunk` (to get to a single commit)? Then I'll test locally (looks like it'll be quick to test and merge).

**Comment by HalosGhost** [comment]
Can this be appropriately rebased ~~and cherry-pick dc7dcc52e5c812827138ce5b3bc0d81b626b4589~~? I just got a chance to test and this PR ~~including that commit~~ corrects the clean-build issue. I'd love to get that merged ASAP (possibly today if you have time to ~~cherry-pick and~~ rebase).

**Comment by HalosGhost** [comment]
@pr4u4t I'd really like to get this merged ASAP. I'm happy to help you get it appropriately rebased and squashed, or I can cherry-pick your commits to a new branch, and merge it separately if that would be easier. Given that `trunk` is actually broken for anyone without an appropriate env already setup, I'll probably move forward with the later option in the next few days if I don't hear back.

**Comment by pr4u4t** [comment]
I may find time today or tomorrow to make a rebase I was busy with a thing that you mentioned in #176. I'm not that mad to shell client-cli. Command results for restd needs to be convertible to json or xml, for that I needed to create utility class to store command result take a look [here](https://github.com/pr4u4t/opencbdc-tx/commit/ca5504b6d256992a2514a2c26e4fb8028a94ebeb). I also see a possibility to use TypedData for storing configuration #173. Configuration file may be designed to be more structured like the one from nginx or lighttpd and parsed using flex, bison couple. It's possible because configuration options are not deAlthough this interface is not yet complete as I need to make map and vector shared to get rid of copying.

**Comment by HalosGhost** [comment]
@pr4u4t I actually went ahead and setup a branch with the cherry-picking, rebasing/squashing done in case I didn't hear back. If you want to take a look and reconfirm your sign-off, I'd happily open a new PR from that branch and get it merged ASAP: https://github.com/mit-dci/opencbdc-tx/commit/afc129d406d3a53cbda5b9fd362cb7acc6eb881e

Note that there's really only one substantive change from what you submitted (squashing/commit-message/whitespace aside): the cmake `find_library` call didn't work for me correctly unless I referred to `snappy` rather than `snappy_compress`.

**Comment by pr4u4t** [comment]
I don't mind unless this changes gets commited. What is really interesting that both `snappy` and `snappy_compress`options work for me. While we can consider that as resolved, let's focus on changes that I've proposed for command handling as there is still more work to do.

**Comment by HalosGhost** [comment]
I've opened the new PR and will merge it as soon as it has >0 tested ACKs. Once it's merged, it will make sense for you to rebase your other PR(s) on top of it so they all have a shared base.

As for which things it makes sense to merge after that, I'll take another review ASAP.

**Pull request closed without merging**
